### ISSUE TITLE
[버그 수정]/ 질문 카테고리 모달/ 카테고리 리스트업을 보여주는 모달창의 크기 문제

### ISSUE THREAD

**Issue by TopazKang** [Onsamiro-Welfare-service/onsaemiro_reactWeb#41]
- 문제가 생긴 부분에 대한 사진 첨부
![image](https://github.com/Onsamiro-Welfare-service/onsaemiro_reactWeb/assets/43803863/8a9d1f85-8c28-4a3a-b9fd-50c24e3d6c9b)

- 설명: 
리스트의 수가 크기에 비해 많아서 그런지 모달창의 하얀 배경을 넘어서는 문제가 있습니다. 이 부분에 대하여 스크롤이나 크기의 변동을 통해서 해결이 필요할 것 같아 이슈 남깁니다.

**Comment by WWvision** [comment]
해당 컴포넌트에 오버플로우 스타일이 적용되어 있지 않다는 것을 발견하였고, 정상적으로 스타일을 적용하였습니다.
